/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Stale mapping",
  "description": "Shows facts about stale bread.",
  "tags": [],
  "enabledByDefault": true,
  "credits": [
    {
      "name": "TheTricker",
      "link": "https://scratch.mit.edu/users/scroch13/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "stalemapping.js"
    }
  ]
};
export default manifest;
